export const equipmentData = [
  {
    id: "EX-302",
    name: "Excavator CAT 320D",
    category: "Heavy",
    status: "In Use",
    statusColor: "text-green-600",
    dotColor: "bg-green-500",
    project: "ABC Warehouse",
    location: "Pune Site",
    hours: "128h",
    nextDue: "20-Apr",
  },
  {
    id: "CM-104",
    name: "Concrete Mixer 350L",
    category: "Medium",
    status: "Under Maintenance",
    statusColor: "text-orange-600",
    dotColor: "bg-orange-500",
    project: "-",
    location: "Yard",
    hours: "-",
    nextDue: "15-Apr",
  },
  {
    id: "DG-65",
    name: "Diesel Generator 65kVA",
    category: "Medium",
    status: "Breakdown",
    statusColor: "text-red-600",
    dotColor: "bg-red-500",
    project: "Metro Cast",
    location: "Ahmedabad",
    hours: "412h",
    nextDue: "Overdue",
  },
  {
    id: "EX-302",
    name: "Excavator CAT 320D",
    category: "Heavy",
    status: "In Use",
    statusColor: "text-green-600",
    dotColor: "bg-green-500",
    project: "ABC Warehouse",
    location: "Pune Site",
    hours: "128h",
    nextDue: "20-Apr",
  },
  {
    id: "CM-104",
    name: "Concrete Mixer 350L",
    category: "Medium",
    status: "Under Maintenance",
    statusColor: "text-orange-600",
    dotColor: "bg-orange-500",
    project: "-",
    location: "Yard",
    hours: "-",
    nextDue: "15-Apr",
  },
  {
    id: "DG-65",
    name: "Diesel Generator 65kVA",
    category: "Medium",
    status: "Breakdown",
    statusColor: "text-red-600",
    dotColor: "bg-red-500",
    project: "Metro Cast",
    location: "Ahmedabad",
    hours: "412h",
    nextDue: "Overdue",
  },
  {
    id: "CM-104",
    name: "Concrete Mixer 350L",
    category: "Medium",
    status: "Under Maintenance",
    statusColor: "text-orange-600",
    dotColor: "bg-orange-500",
    project: "-",
    location: "Yard",
    hours: "-",
    nextDue: "15-Apr",
  },
];
