export const equipmentData = [
  {
    id: "EX-302",
    name: "Excavator CAT 320D",
    category: "Heavy",
    status: "In Use",
    statusColor: "text-green-600",
    dotColor: "bg-green-500",
    project: "ABC Warehouse",
    location: "Pune Site",
    hours: "128h",
    nextDue: "20-Apr",
  },
  {
    id: "CM-104",
    name: "Concrete Mixer 350L",
    category: "Medium",
    status: "Under Maintenance",
    statusColor: "text-orange-600",
    dotColor: "bg-orange-500",
    project: "-",
    location: "Yard",
    hours: "-",
    nextDue: "15-Apr",
  },
  {
    id: "DG-65",
    name: "Diesel Generator 65kVA",
    category: "Medium",
    status: "Breakdown",
    statusColor: "text-red-600",
    dotColor: "bg-red-500",
    project: "Metro Cast",
    location: "Ahmedabad",
    hours: "412h",
    nextDue: "Overdue",
  },
  {
    id: "EX-302",
    name: "Excavator CAT 320D",
    category: "Heavy",
    status: "Completed",
    statusColor: "text-green-600",
    dotColor: "bg-green-500",
    project: "ABC Warehouse",
    location: "Pune Site",
    hours: "128h",
    nextDue: "20-Apr",
  },
  {
    id: "CM-104",
    name: "Concrete Mixer 350L",
    category: "Medium",
    status: "Under Maintenance",
    statusColor: "text-orange-600",
    dotColor: "bg-orange-500",
    project: "-",
    location: "Yard",
    hours: "-",
    nextDue: "15-Apr",
  },
  {
    id: "DG-65",
    name: "Diesel Generator 65kVA",
    category: "Medium",
    status: "Breakdown",
    statusColor: "text-red-600",
    dotColor: "bg-red-500",
    project: "Metro Cast",
    location: "Ahmedabad",
    hours: "412h",
    nextDue: "Overdue",
  },
  {
    id: "CM-104",
    name: "Concrete Mixer 350L",
    category: "Medium",
    status: "Under Maintenance",
    statusColor: "text-orange-600",
    dotColor: "bg-orange-500",
    project: "-",
    location: "Yard",
    hours: "-",
    nextDue: "15-Apr",
  },
];

export const usage_tracking_data = [
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    operator: "Suresh",
    site: "Pune",
    hours: "8h",
    fuel: "22L",
    notes: "Excavation work",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    operator: "Suresh",
    site: "Mumbai",
    hours: "8h",
    fuel: "22L",
    notes: "Excavation work",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    operator: "Satish",
    site: "Pune",
    hours: "8h",
    fuel: "22L",
    notes: "Excavation work",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    operator: "Naresh",
    site: "Nagpur",
    hours: "8h",
    fuel: "22L",
    notes: "Excavation work",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    operator: "Suresh",
    site: "Pune",
    hours: "8h",
    fuel: "22L",
    notes: "Excavation work",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    operator: "Suresh",
    site: "Nagpur",
    hours: "8h",
    fuel: "22L",
    notes: "Excavation work",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    operator: "Suresh",
    site: "Pune",
    hours: "8h",
    fuel: "22L",
    notes: "Excavation work",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    operator: "Suresh",
    site: "Mumbai",
    hours: "8h",
    fuel: "22L",
    notes: "Excavation work",
  },
];

export const equipment_status_data = [
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Heavy",
    assigned_to: "ABC Warehouse",
    usage: "128 hrs",
    location: "Pune Site",
    status: "🟢 In Use",
    gps: "Active",
    nextDue: "20-Apr",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Medium",
    assigned_to: "ABC Warehouse",
    usage: "18 hrs",
    location: "Indore Site",
    status: "🟡 Idle",
    gps: "offline",
    nextDue: "20-Apr",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Heavy",
    assigned_to: "ABC Warehouse",
    usage: "128 hrs",
    location: "Mumbai",
    status: "🔴 Breakdown",
    gps: "Active",
    nextDue: "20-Apr",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Medium",
    assigned_to: "ABC Warehouse",
    usage: "18 hrs",
    location: "Indore Site",
    status: "🟡 Idle",
    gps: "offline",
    nextDue: "20-Apr",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Heavy",
    assigned_to: "ABC Warehouse",
    usage: "128 hrs",
    location: "Pune Site",
    status: "🟢 In Use",
    gps: "Active",
    nextDue: "20-Apr",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Medium",
    assigned_to: "ABC Warehouse",
    usage: "18 hrs",
    location: "Indore Site",
    status: "🟡 Idle",
    gps: "offline",
    nextDue: "20-Apr",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Heavy",
    assigned_to: "ABC Warehouse",
    usage: "128 hrs",
    location: "Pune Site",
    status: "🟢 In Use",
    gps: "Active",
    nextDue: "20-Apr",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Heavy",
    assigned_to: "ABC Warehouse",
    usage: "128 hrs",
    location: "Pune Site",
    status: "🟢 In Use",
    gps: "Active",
    nextDue: "20-Apr",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Medium",
    assigned_to: "ABC Warehouse",
    usage: "18 hrs",
    location: "Indore Site",
    status: "🟡 Idle",
    gps: "offline",
    nextDue: "20-Apr",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Heavy",
    assigned_to: "ABC Warehouse",
    usage: "128 hrs",
    location: "Pune Site",
    status: "🟢 In Use",
    gps: "Active",
    nextDue: "20-Apr",
  },
  {
    id: "EX-302",
    date: "12-Apr",
    equipment: "Excavator CAT 320D",
    category: "Medium",
    assigned_to: "ABC Warehouse",
    usage: "18 hrs",
    location: "Indore Site",
    status: "🟡 Idle",
    gps: "offline",
    nextDue: "20-Apr",
  },
];
